INSERT INTO user (name, username, password, role) VALUES ('Zsofi', 'zsofi', '$2a$04$YDiv9c./ytEGZQopFfExoOgGlJL6/o0er0K.hiGb5TGKHUL8Ebn..', 'ROLE_ADMIN');

INSERT INTO PIZZA(NAME) VALUES('Magyaros');
INSERT INTO PIZZA(NAME) VALUES('SonGoKu');
INSERT INTO BASKET(USER_ID) VALUES(1);

INSERT INTO INGREDIENT(NAME, PIZZA_ID) VALUES('kolbi', 1);
INSERT INTO INGREDIENT(NAME, PIZZA_ID) VALUES('sajt', 1);

INSERT INTO BASKET_PIZZA(BASKET_ID, PIZZA_ID) VALUES(1,1);